# Generated by Django 2.0.2 on 2018-02-28 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('assigned_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('assignees', models.ManyToManyField(to='assignment_system.Assignee')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High'), ('u', 'Urgent')], default='l', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assignment_system.AssignmentPriority'),
        ),
    ]
