# Generated by Django 2.0.2 on 2018-03-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('priority_level', models.CharField(choices=[('l', 'НИЗЬКИЙ'), ('m', 'СЕРЕДНІЙ'), ('h', 'ВИСОКИЙ'), ('u', 'ТЕРМІНОВО')], default='l', max_length=6)),
                ('assigned_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('assignees', models.ManyToManyField(to='assignment_system.Assignee')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment_system.Attachment'),
        ),
    ]
