# Generated by Django 2.0.2 on 2018-04-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFinished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_system.Assignee', verbose_name='Виконувач')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_system.Assignment', verbose_name='Доручення')),
            ],
        ),
    ]
