# Generated by Django 2.0.2 on 2018-03-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='priority',
        ),
        migrations.AddField(
            model_name='assignment',
            name='priority_level',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High'), ('u', 'Urgent')], default='l', max_length=6),
        ),
        migrations.DeleteModel(
            name='AssignmentPriority',
        ),
    ]
