# Generated by Django 2.0.2 on 2018-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0002_assignmentfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='position',
            field=models.TextField(default='викладач'),
        ),
    ]
