# Generated by Django 2.0.2 on 2018-03-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0002_auto_20180310_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
