# Generated by Django 2.0.2 on 2018-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0003_auto_20180310_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignee',
            name='name',
            field=models.TextField(),
        ),
    ]
