# Generated by Django 2.0.2 on 2018-03-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0004_auto_20180310_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
