# Generated by Django 2.0.2 on 2018-03-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0005_auto_20180311_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='name',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
