# Generated by Django 2.0.2 on 2018-03-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0006_auto_20180311_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
