# Generated by Django 2.0.2 on 2018-05-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0007_auto_20180506_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='attachment',
        ),
    ]
