# Generated by Django 2.0.2 on 2018-03-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0011_auto_20180311_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='task_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_system.TaskOwner'),
        ),
    ]
