# Generated by Django 2.0.2 on 2018-03-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0012_auto_20180311_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskowner',
            name='patronymic',
            field=models.CharField(max_length=30),
        ),
    ]
