# Generated by Django 2.0.2 on 2018-03-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0013_auto_20180311_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignees',
            field=models.ManyToManyField(to='assignment_system.Assignee', verbose_name='Виконувачі'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='task_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment_system.TaskOwner'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
