# Generated by Django 2.0.2 on 2018-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0014_auto_20180311_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskowner',
            name='position',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
