# Generated by Django 2.0.2 on 2018-03-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0016_directive_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='directive',
            name='task_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment_system.TaskOwner'),
        ),
        migrations.AddField(
            model_name='post',
            name='task_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment_system.TaskOwner'),
        ),
    ]
