# Generated by Django 2.0.2 on 2018-04-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0017_auto_20180311_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='role',
            field=models.CharField(choices=[('sv', 'КЕРІВНИК'), ('sc', 'СЕКРЕТАР'), ('ja', 'ВИКОНУВАЧ')], default='ja', max_length=6),
        ),
    ]
